"""add email templates and delivery logs

Revision ID: b2407287dea4
Revises: 76b3406297d8
Create Date: 2026-06-19 22:47:20.564016

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b2407287dea4'
down_revision: Union[str, None] = '76b3406297d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_email_templates_company_code')
    )
    op.create_index(op.f('ix_email_templates_code'), 'email_templates', ['code'], unique=False)
    op.create_index(op.f('ix_email_templates_company_id'), 'email_templates', ['company_id'], unique=False)
    op.create_table('email_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_delivery_logs_company_id'), 'email_delivery_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_delivery_logs_recipient_email'), 'email_delivery_logs', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_delivery_logs_template_id'), 'email_delivery_logs', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_delivery_logs_template_id'), table_name='email_delivery_logs')
    op.drop_index(op.f('ix_email_delivery_logs_recipient_email'), table_name='email_delivery_logs')
    op.drop_index(op.f('ix_email_delivery_logs_company_id'), table_name='email_delivery_logs')
    op.drop_table('email_delivery_logs')
    op.drop_index(op.f('ix_email_templates_company_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_code'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
